# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'capybara/cucumber'
require 'selenium-webdriver'

# Increase wait time – very important for React (components mount asynchronously)
Capybara.default_max_wait_time = 10

# Optional: make tests slower but more reliable with React
Capybara.default_normalize_ws = true


Capybara.register_driver :selenium_chrome_headless do |app|
  options = Selenium::WebDriver::Chrome::Options.new


  options.add_argument('--headless')
  options.add_argument('--no-sandbox')
  options.add_argument('--disable-dev-shm-usage')
  options.add_argument('--disable-gpu')

  Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)
end

# 將 Cucumber 的 JavaScript 驅動器指向我們剛設定好的 Headless Chrome
Capybara.javascript_driver = :selenium_chrome_headless
Capybara.default_driver = :selenium_chrome_headless


# ==========================================
# 2. Rails 錯誤處理設定
# ==========================================
# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail.
ActionController::Base.allow_rescue = false


# ==========================================
# 3. 資料庫清理設定 (DatabaseCleaner)
# ==========================================
# Remove/comment out the lines below if your app doesn't have a database.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

After do |scenario|
  if scenario.failed?
    save_and_open_screenshot   # or Capybara::Screenshot
    save_page                  # saves the HTML
  end
end
